name: Continuous Integration

on: [pull_request]

jobs:
# Service
  # Dependencies
  serviceDependencies:
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Install Node
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        working-directory: ./service
        id: npm-cache
        with:
          path: node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

      # Install Dependencies
      - name: Install Dependencies
        working-directory: ./service
        run: npm install

  # Lint
  serviceLint:
    needs: serviceDependencies
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        working-directory: ./service
        id: npm-cache
        with:
          path: node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

        # Lint
      - name: Lint
        working-directory: ./service
        run: npm run lint

  # Build
  serviceBuild:
    needs: serviceDependencies
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Install Node
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Prisma Generate
      - name: Prisma Generate
        working-directory: ./service
        run: npx prisma:generate

      # Build
      - name: Build
        run: npm run build

  # Test
  serviceTest:
    needs: serviceDependencies
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: node-modules-${{ hashfiles('service/package-lock.json') }}

      # # Prisma Generate
      # - name: Prisma Generate
      #   run: yarn prisma:generate

        # Test
      - name: Test
        run: npm run test

# API
  #  Dependencies
  api-gatewayDependencies:
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Install Node
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        working-directory: ./api-gateway
        id: npm-cache
        with:
          path: node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

      # Install Dependencies
      - name: Install Dependencies
        working-directory: ./api-gateway
        run: npm install

  # Lint
  api-gatewayLint:
    needs: api-gatewayDependencies
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        working-directory: ./api-gateway
        id: npm-cache
        with:
          path: node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

        # Lint
      - name: Lint
        working-directory: ./api-gateway
        run: npm run lint

  # Build
  api-gatewayBuild:
    needs: api-gatewayDependencies
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Install Node
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        working-directory: ./api-gateway
        id: npm-cache
        with:
          path: node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

      # Install Dependencies
      - name: Install Dependencies
        working-directory: ./api-gateway
        run: npm install

      # Build
      - name: Build
        working-directory: ./api-gateway
        run: npm run build

  # Test
  api-gatewayTest:
    needs: api-gatewayDependencies
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: node-modules-${{ hashfiles('api-gateway/package-lock.json') }}

      # # Prisma Generate
      # - name: Prisma Generate
      #   run: yarn prisma:generate

        # Test
      - name: Test
        run: npm run test