name: Continuous Integration

on: [pull_request]

jobs:
# Service
  # Dependencies
  serviceDependencies:
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Install Node
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: service/node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

      # Install Dependencies
      - name: Install Dependencies
        run: |
          cd service
          npm install

      - name: List
        working-directory: ./service
        run: ls

  # Build
  serviceBuild:
    needs: serviceDependencies
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Install Node
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: service/node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

      - name: List
        working-directory: ./service
        run: ls

      # Install Dependencies
      - name: Install Dependencies
        run: |
          cd service
          npm install

      # Prisma Generate
      # - name: Prisma Generate
      #   run: |
      #     cd service
      #     npx prisma:generate

      # Build
      - name: Build
        run: |
          cd service
          npm run build

  # Test
  serviceTest:
    needs: serviceDependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service
    steps:
      # Pull Repository
      - name: Pull Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: service/node_modules
          key: node-modules-${{ hashfiles('service/package-lock.json') }}

      # # Prisma Generate
      # - name: Prisma Generate
      #   run: yarn prisma:generate

        # Test
      - name: Test
        run: |
          cd service
          npm run test

# API
  #  Dependencies
  api-gatewayDependencies:
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Install Node
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: api-gateway/node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

      # Install Dependencies
      - name: Install Dependencies
        run: |
          cd api-gateway
          npm install

  # Build
  api-gatewayBuild:
    needs: api-gatewayDependencies
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Install Node
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: api-gateway/node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

      # Install Dependencies
      - name: Install Dependencies
        run: |
          cd api-gateway
          npm install

      # Build
      - name: Build
        run: |
          cd api-gateway
          npm run build

  # Test
  api-gatewayTest:
    needs: api-gatewayDependencies
    runs-on: ubuntu-latest
    steps:
      # Pull Repository
      - name: Pull Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch Branch
      - name: Fetch ${{github.head_ref}}
        run: git fetch origin ${{github.head_ref}}

      # Get Cached Dependencies
      - name: Get Cached Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: api-gateway/node_modules
          key: node-modules-${{ hashfiles('package-lock.json') }}

      # # Prisma Generate
      # - name: Prisma Generate
      #   run: yarn prisma:generate

        # Test
      - name: Test
        run: |
          cd api-gateway
          npm run test